version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            export PIPENV_VENV_IN_PROJECT=1
            pipenv install --dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            export PIPENV_VENV_IN_PROJECT=1
            pipenv run pytest
